autoindex.php
thelia-modules/RewriteUrl pull request #34
Opened 2021-05-31 09:18 UTC by LucasCRENAIS

2021-06-01 16:52 UTC, gillesbourgeat requested changes

2021-06-01 16:52 UTC, gillesbourgeat commented on Config/config.xml
> +
```suggestion
```

Pas besoin de déclarer le listener 2 fois.  
A noter, qu'un service qui a le meme id qu'un autre sera ignoré.  
Les id de service doivent être unique.

2021-06-01 16:52 UTC, gillesbourgeat commented on Config/config.xml
> +        <service id="https.redirection.action" class="RewriteUrl\EventListeners\RequestListener">
```suggestion
        <service id="rewriteurl.request.listener" class="RewriteUrl\EventListeners\RequestListener">
```

Dans le cas des modules, l'id doit contenir le nom du module, cela évite d'avoir des collisions d'id avec d'autres modules.

2021-06-01 16:52 UTC, gillesbourgeat commented on Controller/Admin/ModuleConfigController.php
> +        $isIndexRedirectionEnabled = ConfigQuery::isIndexRedirectionEnable();
On va stocker les valeurs de configuration dans la table config_module pour éviter de poluer la table config de Thelia.  
Tu peux utiliser la classe principale de ton module qui contient les méthodes statiques `setConfigValue` et `getConfigValue` `RewriteUrl::getConfigValue(....`  
Le cas de `isRewritingEnable` est différent, c'est une configuration interne à Thelia, c'est pour cela qu'elle est dans la table config principale de Thelia.

2021-06-01 16:52 UTC, gillesbourgeat commented on Controller/Admin/ModuleConfigController.php
> +            ConfigQuery::write("index_redirection_enable", $isIndexRedirectionEnable ? 1 : 0);
Changer pour utiliser la table module_config avec RewriteUrl::setConfigValue(....

2021-06-01 16:52 UTC, gillesbourgeat commented on Controller/Admin/ModuleConfigController.php
> +            ConfigQuery::write("https_redirection_enable", $isHttpsRedirectionEnable ? 1 : 0);
Changer pour utiliser la table module_config avec RewriteUrl::setConfigValue(....

2021-06-01 16:52 UTC, gillesbourgeat commented on EventListeners/RequestListener.php
> +        if (ConfigQuery::isHttpsRedirectionEnable())
idem que `isIndexRedirectionEnable`

2021-06-01 16:52 UTC, gillesbourgeat commented on EventListeners/RequestListener.php
> +                $securePath = str_replace('http', 'https', $fullPath) ;
Plutôt utiliser un preg_replace avec un `/^http/`, cela va éviter d'avoir des problèmes si il y a une autre string http au milieu de l'url.

Exemple avec preg_replace : `preg_replace("/^http:/i", "https:", $url)`

2021-06-01 16:52 UTC, gillesbourgeat commented on EventListeners/RequestListener.php
> +            if (!$request->isSecure())
```suggestion
            if (!$event->getRequest()->isSecure()) 
```
Tu peux directement écrire cela, pas obligé de stocker dans une variable si le retour est utilisé qu'à un seul endroit.   
Idem pour la variable `$fullPath`

2021-06-01 17:09 UTC, gillesbourgeat requested changes

2021-06-01 17:09 UTC, gillesbourgeat commented on Controller/Admin/ModuleConfigController.php
> +            ), 500);
```suggestion
            ), 400);
```
C'est une erreur 400, car dans ton cas, si `$isIndexRedirectionEnable` est null, c'est que la requete n'est pas valide.  
https://developer.mozilla.org/fr/docs/Web/HTTP/Status/400  

Idem pour la méthode setHttpsRedirectionEnableAction.  

Tu peux aussi le corriger pour la méthode setRewritingEnableAction.

Et si tu veux même utiliser les bonnes pratiques, tu peux remplacer ce code
```php
return $this->jsonResponse(Translator::getInstance()->trans(
                "Unable to change the configuration variable.",
                [],
                RewriteUrl::MODULE_DOMAIN
            ), 500);
```
par
```
throw new BadRequestHttpException('Missing index_redirection_enable parameter in url');
```
Le Kernel symfony va intercepter cette exception pour créer une réponse 400 avec le message.  
Tu peux aussi réorganiser ce code pour virer le `else`.  
Et pas besoin de traduire cette erreur, en théorie elle n'est pas visible pour un simple utilisateur.  Et quand l'erreur est destinée à des développeurs, l'anglais est largement suffisant.

2021-06-01 17:29 UTC, gillesbourgeat requested changes

2021-06-01 17:29 UTC, gillesbourgeat commented on Config/config.xml
> +    <!-- ##################### -->
```suggestion
```
Tu peux retirer les commentaires, dans ce cas, la lecture du code doit se suffire à elle même

2021-06-01 17:29 UTC, gillesbourgeat commented on EventListeners/RequestListener.php
> +    // event to listen to
```suggestion
```
Commentaire inule

2021-06-01 17:29 UTC, gillesbourgeat commented on EventListeners/RequestListener.php
> +    // permanently redirect request if url contain $regexToMatch string
Si tu veux mettre un commentaire à une méthode, préférer la syntaxe
```php
/**
mon commentaire
*/
```
il manque 2,3 infos dans le commentaire

2021-06-01 17:29 UTC, gillesbourgeat commented on templates/backOffice/default/RewriteUrl/module-configuration.html
> +            <!-- index.php redirection switch -->
Dans le cas du html, le commentaire est en effet une bonne idée, ça aide à se repérer.  
par contre pour la fermeture de la div, il est préférable de donner plus d'info
exemple : 
`<!-- end of index.php redirection switch -->`
à la place de 
`<!-- ################################-->`

Pour info, tu peux aussi faire des commentaires en smarty qui ne seront pas visibles après la compilation du code, c'est des commentaires visibles uniquement par les devs.  
```smarty
{* A Smarty comment *}
```

2021-06-22 09:58 UTC, lopes-vincent commented on Config/routing.xml
> +
```suggestion

        <route id="rewrite.url.config.set-index-redirection_enable" path="/admin/module/RewriteUrl/config/setIndexRedirectionEnable">
        <default key="_controller">RewriteUrl\Controller\Admin\ModuleConfigController::setIndexRedirectionEnableAction</default>
    </route>

    <route id="rewrite.url.config.set-https-redirection_enable" path="/admin/module/RewriteUrl/config/setHttpsRedirectionEnable">
        <default key="_controller">RewriteUrl\Controller\Admin\ModuleConfigController::setHttpsRedirectionEnableAction</default>
    </route>
```

2026-08-12 13:09 UTC, closed without merging